<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="..\Packages\AssetRipper.Bindings.LLVM.Linux.Arm64\AssetRipper.Bindings.LLVM.Linux.Arm64.csproj" />
		<ProjectReference Include="..\Packages\AssetRipper.Bindings.LLVM.Linux.X64\AssetRipper.Bindings.LLVM.Linux.X64.csproj" />
		<ProjectReference Include="..\Packages\AssetRipper.Bindings.LLVM.Mac.Arm64\AssetRipper.Bindings.LLVM.Mac.Arm64.csproj" />
		<ProjectReference Include="..\Packages\AssetRipper.Bindings.LLVM.Windows.X64\AssetRipper.Bindings.LLVM.Windows.X64.csproj" />
	</ItemGroup>
</Project>
