<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>

		<PackageId>AssetRipper.Bindings.LLVM</PackageId>
		<Description>Multi-platform bindings for libLLVM</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<NoWarn>$(NoWarn);SYSLIB1054</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Packages\AssetRipper.Bindings.LLVM.Linux.Arm64\AssetRipper.Bindings.LLVM.Linux.Arm64.csproj" />
		<ProjectReference Include="..\Packages\AssetRipper.Bindings.LLVM.Linux.X64\AssetRipper.Bindings.LLVM.Linux.X64.csproj" />
		<ProjectReference Include="..\Packages\AssetRipper.Bindings.LLVM.Mac.Arm64\AssetRipper.Bindings.LLVM.Mac.Arm64.csproj" />
		<ProjectReference Include="..\Packages\AssetRipper.Bindings.LLVM.Windows.Arm64\AssetRipper.Bindings.LLVM.Windows.Arm64.csproj" />
		<ProjectReference Include="..\Packages\AssetRipper.Bindings.LLVM.Windows.X64\AssetRipper.Bindings.LLVM.Windows.X64.csproj" />
	</ItemGroup>
</Project>
