name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { os: windows-latest, runtime: win-x64 }
          - { os: ubuntu-latest, runtime: linux-x64 }

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Set up Clang
        if: matrix.config.runtime == 'linux-x64' || matrix.config.runtime == 'linux-arm64'
        uses: egor-tensin/setup-clang@v2
        with:
          version: 21

      - name: Setup LLD
        if: matrix.config.runtime == 'linux-x64' || matrix.config.runtime == 'linux-arm64'
        run: sudo apt install lld-21

      - name: Build
        run: dotnet build

      - name: Download LLVM
        run: dotnet run --project ./AssetRipper.Bindings.LLVM.Downloader/AssetRipper.Bindings.LLVM.Downloader.csproj 21.1.8 ${{ matrix.config.runtime }}

      - name: List LLVM Directory
        run: ls -R ${{ github.workspace }}/AssetRipper.Bindings.LLVM.Downloader/bin/Debug/net10.0/llvm

      - name: Set LLVM Path
        id: get-llvm-path
        shell: bash
        run: |
          echo "llvm_path=${GITHUB_WORKSPACE}/AssetRipper.Bindings.LLVM.Downloader/bin/Debug/net10.0/llvm" >> $GITHUB_OUTPUT

      - name: Build Native Library (Windows)
        if: matrix.config.runtime == 'win-x64' || matrix.config.runtime == 'win-arm64'
        run: |
          cmake -S ./Native -B ./Native/build -DLLVM_ROOT="${{ steps.get-llvm-path.outputs.llvm_path }}"
          cmake --build ./Native/build --config Release

      - name: Build Native Library (Linux)
        if: matrix.config.runtime == 'linux-x64' || matrix.config.runtime == 'linux-arm64'
        run: |
          cmake -S ./Native -B ./Native/build -DLLVM_ROOT="${{ steps.get-llvm-path.outputs.llvm_path }}" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld"
          cmake --build ./Native/build --config Release

      - name: Build Native Library (MacOS)
        if: matrix.config.runtime == 'osx-arm64'
        run: |
          cmake -S ./Native -B ./Native/build -DLLVM_ROOT="${{ steps.get-llvm-path.outputs.llvm_path }}"
          cmake --build ./Native/build --config Debug

      - name: List Native Directory
        run: ls -R ${{ github.workspace }}/Native

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: libLLVM_${{ matrix.config.runtime }}
          path: |
            ./Native/build/Debug/libLLVM.*
            ./Native/build/Release/libLLVM.*
          if-no-files-found: error
